In [1]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
np.array(my_list) # return 1d array

array([1, 2, 3, 4, 5])

In [5]:
my_2d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_2d_list)  # return 2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.random.rand(5)  ## returns array of 5 random numbers 

array([0.8920996 , 0.38377883, 0.9982726 , 0.65703952, 0.0243852 ])

In [11]:
np.random.rand(3,3)

array([[0.67316229, 0.55355267, 0.74440517],
       [0.72872925, 0.0245291 , 0.42326284],
       [0.07239001, 0.1309966 , 0.72437025]])

In [12]:
np.random.randn(3,3) ## standard normalized number in an array

array([[-0.32993409,  1.06402677,  0.5334197 ],
       [ 0.05599453,  0.15072661,  0.9180932 ],
       [ 0.62711302, -0.8600736 , -0.51503844]])

In [13]:
my_arr = np.random.rand(10)
my_arr

array([0.33085959, 0.13415859, 0.95375875, 0.01638834, 0.14763229,
       0.9882799 , 0.16439927, 0.58879151, 0.59122135, 0.41852968])

In [17]:
my_arr.reshape(5,2) # reshape 1d to 2d array

array([[0.33085959, 0.13415859],
       [0.95375875, 0.01638834],
       [0.14763229, 0.9882799 ],
       [0.16439927, 0.58879151],
       [0.59122135, 0.41852968]])

In [19]:
my_arr2 = np.random.rand(10)
my_arr2

array([0.44049704, 0.45669352, 0.84853083, 0.56697137, 0.39466781,
       0.2535543 , 0.99602044, 0.30533534, 0.09347104, 0.73511487])

In [20]:
my_arr2.max() ## get the max in an array

0.9960204374026377

In [21]:
my_arr2.min()

0.09347103809675494

In [22]:
my_arr2.argmax() # gets the index position of the maximum in an array

6

In [23]:
my_arr2.argmin() # gets the index position of the minimum in an array

8

In [24]:
myarr2_reshaped = my_arr2.reshape(5,2)
myarr2_reshaped

array([[0.44049704, 0.45669352],
       [0.84853083, 0.56697137],
       [0.39466781, 0.2535543 ],
       [0.99602044, 0.30533534],
       [0.09347104, 0.73511487]])

In [25]:
myarr2_reshaped.max()

0.9960204374026377

In [26]:
myarr2_reshaped.argmax()

6

In [28]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
myarr2_reshaped.shape ## shape of an array

(5, 2)

In [32]:
myarr2_reshaped.size ## size of an array

10

In [34]:
myarr2_reshaped.dtype ## return the datatype of an array

dtype('float64')

In [35]:
identity_matrix.dtype

dtype('float64')

In [36]:
from numpy.random import randint

In [40]:
randint(1,10)

5

In [44]:
### slicing and dicing in arrays

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[9]

9

In [47]:
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr2 = arr.copy()
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr2[:5] = 200
arr2

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
arr2d = np.array([[10,12,14],[23,24,26],[34,35,36]])
arr2d

array([[10, 12, 14],
       [23, 24, 26],
       [34, 35, 36]])

In [56]:
arr2d[1][2]

26

In [59]:
arr2d.shape

(3, 3)

In [61]:
arr2d[2,2]

36

In [64]:
###

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
bool_arr = arr>5

In [66]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [67]:
arr[bool_arr] ## return the value at index of the array : arr

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr>5]  ## returns the value at index of the array : arr (*important for pandas)

array([ 6,  7,  8,  9, 10])

In [70]:
### operations in np array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr + 20

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [73]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr / arr

/Users/rishushrivastava/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [77]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [78]:
np.max(arr)

10

In [79]:
arr.max()

10